### PR TITLE
Create GameOfLife

### PR DESCRIPTION
**Pull request by RayotiKar**
Hope the pr gets accepted :).

### CODE REVIEW

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@RayotiKar Extension of the file is missing and directory of the file is missing

**Comment by RayotiKar** [comment]
A new commit is created as per the required changes. Hope it's fine now & gets accepted :).

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@RayotiKar Remove the older file that is without extension

**Comment by RayotiKar** [comment]
> @RayotiKar Remove the older file that is without extension

Done. Please check for it once & update me further.

**Review by siddharth25pandey — APPROVED** [review]
@RayotiKar  LGTM 💯 
Able to merge
Thanks!

**Comment by siddharth25pandey** [comment]
@all-contributors please add @RayotiKar for her code

**Pull request merged**
