### PR TITLE
Added Min Jumps DP problem 

### PR DESCRIPTION
**Pull request by karthick191999**
Added a Min Jumps DP problem pls review and merge it @siddharth25pandey

### CODE REVIEW

**Review by siddharth25pandey — APPROVED** [review]
@karthick191999 Good to go
Able to merge
Thanks!

**Comment by siddharth25pandey** [comment]
@all-contributors please add @karthick191999 for his code

**Comment by siddharth25pandey** [comment]
@karthick191999 Add the file into respective folder

**Comment by karthick191999** [comment]
@siddharth25pandey add it to the DP file ??

**Comment by siddharth25pandey** [comment]
@karthick191999 Yes, add it into DP Folder by creating a new PR

**Pull request merged**
