### PR TITLE
Adding DNF Sort

### PR DESCRIPTION
**Pull request by Aarav-Nigam**
I am adding a fundamental sort which is used to sort an array  with 3 different types of elements.
Please merge this branch to master branch.

### CODE REVIEW

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@Aarav-Nigam Remove the JSON file

**Comment by Aarav-Nigam** [comment]
I have removed the JSON file.

**Comment by Aarav-Nigam** [comment]
I tried deleting it
But I am not getting it.
The delete button is disabled for the .exe files
Should I delete this PR and make a new one
Or is there any other way

**Comment by siddharth25pandey** [comment]
> I tried deleting it But I am not getting it. The delete button is disabled for the .exe files Should I delete this PR and make a new one Or is there any other way

@Aarav-Nigam You can directly delete the .exe file

**Pull request closed without merging**
