### PR TITLE
Create Find Minimum in Rotated Sorted Array.cpp

### PR DESCRIPTION
**Pull request by anjalikumawat2002**
Question Link: https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/

### CODE REVIEW

**Comment by anjalikumawat2002** [comment]
@siddhant2202 Please merge this Pull Request.

**Review by siddharth25pandey — APPROVED** [review]
@anjalikumawat2002  LGTM 💯 
Able to merge
Thanks!

**Comment by siddharth25pandey** [comment]
@all-contributors please add @anjalikumawat2002 for her code

**Comment by anjalikumawat2002** [comment]
Thanks, @siddharth25pandey

**Pull request merged**
