### PR TITLE
Added missing_number_in_array.cpp

### PR DESCRIPTION
**Pull request by rithwik003**
Signed-off-by: rithwik003 <amaraneni.rithwik@gmail.com>

### CODE REVIEW

**Comment by rithwik003** [comment]
Hey @siddharth25pandey , I want this PR for Hacktoberfest 2022.

**Comment by rithwik003** [comment]
Issue link : https://github.com/siddharth25pandey/CPP-Programming/issues/447

**Comment by rithwik003** [comment]
@siddharth25pandey can you check my PR once and tell me if there is any issue.

**Review by siddharth25pandey — APPROVED** [review]
@rithwik003 LGTM 💯 
Able to merge
Thanks!

**Comment by siddharth25pandey** [comment]
@all-contributors please add @rithwik003 for his code

**Pull request merged**
