### PR TITLE
Subset Sum problem of DP

### PR DESCRIPTION
**Pull request by stuti-v4**
A Dynamic Programming Question. Plz Add a hacktoberfest label to it.

### CODE REVIEW

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@stuti-v4 Please remove the duplicate file

**Comment by stuti-v4** [comment]
Modified!!

**Comment by stuti-v4** [comment]
i have modified the commits I had made.. @siddharth25pandey

**Review by siddharth25pandey — APPROVED** [review]
@stuti-v4 LGTM
Able to merge
Thanks!

**Comment by stuti-v4** [comment]
Good luck :) @siddharth25pandey

**Pull request merged**
