### PR TITLE
reverse array

### PR DESCRIPTION
**Pull request by laibanasirdev**
reverse array

### CODE REVIEW

**Comment by laibanasirdev** [comment]
its a program by which you can reverse aan array

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@laibanasirdev remove the .vscode extension file

**Review by siddharth25pandey — APPROVED** [review]
@laibanasirdev  LGTM 💯 
Able to merge 
Thanks!

**Comment by siddharth25pandey** [comment]
@all-contributors please add @laibanasirdev for his/her code

**Pull request merged**
