### PR TITLE
Create Binary_Exponentiation.cpp

### LINKED ISSUE #260: Adding Binary Exponentiation
I want to add Binary Exponentiation Iterative method in Maths folder.
Please let me work on this issue

### PR DESCRIPTION
**Pull request by ShaileshKumar007**
Added Binary Exponentiation iterative method in Maths folder.
This PR fixes #260

### CODE REVIEW

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@ShaileshKumar007 Return a main function

**Comment by ShaileshKumar007** [comment]
> @ShaileshKumar007 Return a main function

Done. Let me know if any further changes required.

**Review by siddharth25pandey — APPROVED** [review]
@ShaileshKumar007 Looks good to me
Able to merge now
Thanks!

**Comment by siddharth25pandey** [comment]
@all-contributors please add @ShaileshKumar007  for his code

**Pull request merged**
