### PR TITLE
Inverting a binary tree.

### PR DESCRIPTION
**Pull request by varunsharma21**
This code invert a binary tree that means it will give mirror image of the initial binary tree.
Comments are also added for better understanding.

### CODE REVIEW

**Comment by siddharth25pandey** [comment]
@varunsharma21 Please create a **CPP** file

**Comment by siddharth25pandey** [comment]
Please change the extension of the file as .cpp

**Comment by varunsharma21** [comment]
I have pulled two more request with important questions which have passed all checks.
Please merge them as it will be very helpful.

**Comment by siddharth25pandey** [comment]
@varunsharma21 Do [this](https://github.com/siddharth25pandey/CPP-Programming/pull/142#issuecomment-702916739) first

**Comment by varunsharma21** [comment]
This is already present. So it will create a duplicate.

**Pull request closed without merging**
